{% set name = "dataclasses-json" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataclasses_json-{{ version }}.tar.gz
  sha256: b6b3e528266ea45b9535223bc53ca645f5208833c29229e847b3f26a1cc55fc0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.2.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - typing_inspect >=0.4.0,<1
    - marshmallow >=3.18.0,<4.0.0

test:
  imports:
    - dataclasses_json
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lidatong/dataclasses-json
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easily serialize dataclasses to and from JSON
  doc_url: https://lidatong.github.io/dataclasses-json/
  dev_url: https://github.com/lidatong/dataclasses-json

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
    - mxr-conda
    - rxm7706
